#!/bin/bash
set -eEu
set -o pipefail

# These files are mounted into the runtime container by systemd.
. /etc/devenv/global.conf
. /etc/devenv/user.conf

readonly duo="${DUO:-true}"

# Disable for now.
# To-do: re-enable geoip filter.
#readonly allowed_countries="${ALLOWED_COUNTRIES:-.*}"
#client_ip=${SSH_CLIENT%% *}
#readonly client_ip

if [[ "${duo}" == true ]]; then
  # login_duo handles both interactive and scp.
  exec /usr/sbin/login_duo -c "/etc/duo/${DUO_USERNAME}.conf" -f "${DUO_USERNAME}"
elif [[ -n "${SSH_ORIGINAL_COMMAND:-}" ]]; then
  # Allow scp without duo.
  exec /bin/bash -c "${SSH_ORIGINAL_COMMAND}"
else
  # Interactive shell.
  exec /bin/bash -l
fi
