#!/bin/sh
set -e

DOCKER_VERSION=1.10.3
BUILD_DATE=$(date +%Y%m%dT%H%M)
GIT_REF=$(git rev-parse --short HEAD)
TAG=${BUILD_DATE}-git-${GIT_REF}

# Latest git ref for "state/Dockerfile".
STATE_GIT_REF=$(git rev-list --abbrev-commit --max-count 1 HEAD -- state/Dockerfile)

# Stash variables locally.
(
echo "TAG=${TAG}"
echo "STATE_GIT_REF=${STATE_GIT_REF}"
) > ENV

docker build \
  --rm \
  --build-arg DOCKER_VERSION=${DOCKER_VERSION} \
  --build-arg GIT_REF=${GIT_REF} \
  --build-arg VERSION=${TAG} \
  -t jumanjiman/devenv:ci \
  app/

docker build \
  --rm=false \
  --build-arg GIT_REF=${STATE_GIT_REF} \
  -t jumanjiman/state:ci \
  state/

docker images | grep -e REPOSITORY -e devenv -e state
