#!/bin/sh
set -e

. script/functions

docker login -e ${email} -u ${user} -p ${pass}

if [ -e /dev/shm/publish_state ]; then
  # Latest git ref for "state/Dockerfile".
  STATE_GIT_REF=$(git rev-list --abbrev-commit --max-count 1 HEAD -- state/Dockerfile)

  docker push jumanjiman/state:${STATE_GIT_REF}
fi

for image in $(docker images | awk '/jumanjiman\/devenv/ {print $1":"$2 }'); do
  docker push ${image}
done

docker logout

# Update microbadger metadata for state image.
curl -sS 'https://hooks.microbadger.com/images/jumanjiman/state/K9GX-acN8HGx2rbyQrmn2hI6SQ4='

# Update microbadger metadata for app image.
curl -sS 'https://hooks.microbadger.com/images/jumanjiman/devenv/NPIdqj5J8GhG6vW5H_0RzDAXT_w='
