#!/bin/sh
set -e

. script/functions

docker login -e ${email} -u ${user} -p ${pass}

if [ -x /dev/shm/publish_state ]; then
  docker push jumanjiman/state:${CACHED_REF}
  docker push jumanjiman/state:latest
fi

for image in $(docker images | awk '/jumanjiman\/devenv/ {print $1":"$2 }'); do
  docker push ${image}
done

docker logout
