#!/bin/bash
set -eEu
set -o pipefail

################################################################################
# Configure your local dev environment for this git repo.
# Invoke as "ci/bootstrap".
################################################################################

usage() {
  cat <<EOF
  Usage: "${PROG}" [-dh] [-v VERBOSITY]
    -d            debug, shorthand for -v2
    -h            help (this screen)
    -v VERBOSITY, where VERBOSITY is 0, 1, or 2
EOF
}

main() {
  if command -v pre-commit &> /dev/null; then
    info "pre-commit command is already installed"
  else
    # Install for just this user. Does not need root.
    pip install --user -Iv --compile --no-cache-dir pre-commit
  fi

  pre-commit autoupdate

  # https://git-scm.com/docs/git-gc
  smitty git gc --prune

  smitty git fetch --all --prune
}

################################################################################
# Program execution starts here.
################################################################################

. ci/functions.sh

readonly PROG=$0

# http://wiki.bash-hackers.org/howto/getopts_tutorial
while getopts ":dhv:" opt; do
  case ${opt} in
    d)
      VERBOSITY=2
      ;;
    h)
      usage
      exit 0
      ;;
    v)
      # shellcheck disable=SC2034
      VERBOSITY=${OPTARG}
      ;;
    :)
      usage
      err option -"${OPTARG}" requires an argument
      exit 1
      ;;
    \?|*)
      usage
      err invalid option -"${OPTARG}"
      exit 1
      ;;
  esac
done
readonly VERBOSITY

# After the shift, $* contains non-option arguments.
shift $((OPTIND-1))

main
