#!/bin/bash
set -eEu
set -o pipefail

################################################################################
# Configure your local dev environment for this git repo.
# Invoke as "ci/bootstrap".
################################################################################

. ci/functions.sh

main() {
  setup_python_path

  if command -v pre-commit &>/dev/null; then
    info "pre-commit command is already installed"
  else
    # Install for just this user. Does not need root.
    run pip install --user -Iv --compile --no-cache-dir pre-commit
  fi

  pre-commit autoupdate

  # https://git-scm.com/docs/git-gc
  run git gc --prune

  run git fetch --all --prune

  add_upstream_git_remote
  fetch_upstream
}

setup_python_path() {
  PYTHON_PATH="$(python -c "import site; print(site.USER_BASE)")"
  readonly PYTHON_PATH

  if ! grep "${PYTHON_PATH}/bin" <(printenv PATH) &>/dev/null; then
    export PATH="${PATH}:${PYTHON_PATH}/bin"
  fi
}

add_upstream_git_remote() {
  if ! git remote show upstream &>/dev/null; then
    run git remote add upstream https://github.com/jumanjihouse/devenv.git
  fi
}

fetch_upstream() {
  run git fetch upstream
}

main
