#!/bin/sh
set -e

cat > ci/vars <<EOF
# This file (ci/vars) is automatically created by ci/build and
# is never checked into version control.
export BUILD_DATE=$(date +%Y%m%dT%H%M)
export GIT_REF=$(git rev-parse --short HEAD)
export TAG=\${BUILD_DATE}-git-\${GIT_REF}
export CI_BUILD_URL=${CIRCLE_BUILD_URL}

# Which version of Docker do we install in the image?
export DOCKER_VERSION=17.07.0-r0
EOF

. ci/vars

docker build \
  --rm \
  --build-arg DOCKER_VERSION=${DOCKER_VERSION} \
  --build-arg GIT_REF=${GIT_REF} \
  --build-arg VERSION=${TAG} \
  -t jumanjiman/devenv \
  app/

docker tag jumanjiman/devenv jumanjiman/devenv:${TAG}

# We only want to update the state image when it truly changes.
CACHED_REF=""
if [ -s ~/deps/state.tar ]; then
  echo "=== load cache ==="
  docker load -i ~/deps/state.tar
  CACHED_REF=$(docker inspect -f '{{ index .Config.Labels "org.label-schema.vcs-ref" }}' jumanjiman/state)
  echo "state image after loading cache"
  docker images | grep -e REPOSITORY -e state
fi

# Latest git ref for "state/Dockerfile".
STATE_GIT_REF=$(git rev-list --abbrev-commit --max-count 1 HEAD -- state/Dockerfile)

if [ "x${CACHED_REF}" != "x${STATE_GIT_REF}" ]; then
  docker build \
    --rm=false \
    --build-arg GIT_REF=${STATE_GIT_REF} \
    -t jumanjiman/state \
    state/

  docker tag jumanjiman/state jumanjiman/state:${STATE_GIT_REF}
  touch /dev/shm/publish_state

  if [ -d ~/deps ]; then
    rm -f ~/deps/state.tar || :
    docker save -o ~/deps/state.tar jumanjiman/state jumanjiman/state:${STATE_GIT_REF}
  fi
fi

docker images | grep -e REPOSITORY -e devenv -e state
