#!/bin/bash
set -eEu
set -o pipefail

################################################################################
# Build the images. Invoke as "ci/build".
################################################################################

cat >ci/vars <<EOF
# This file (ci/vars) is automatically created by ci/build and
# is never checked into version control.
declare -rx BUILD_DATE="$(date +%Y%m%dT%H%M)"
declare -rx GIT_REF="$(git rev-parse --short HEAD)"
declare -rx TAG=\${BUILD_DATE}-git-\${GIT_REF}
declare -rx CI_BUILD_URL="${CIRCLE_BUILD_URL:-unknown}"
EOF

. ci/functions.sh
. ci/vars

run docker build \
  --rm \
  --build-arg GIT_REF="${GIT_REF}" \
  --build-arg VERSION="${TAG}" \
  -t jumanjiman/devenv \
  app/

run docker tag jumanjiman/devenv jumanjiman/devenv:"${TAG}"

# We only want to update the state image when it truly changes.
CACHED_REF=""
if [ -s ~/deps/state.tar ]; then
  info "=== load cache ==="
  run docker load -i ~/deps/state.tar
  CACHED_REF=$(docker inspect -f '{{ index .Config.Labels "org.label-schema.vcs-ref" }}' jumanjiman/state)
  info "state image after loading cache"
  run docker images | grep -e REPOSITORY -e state
fi

# Latest git ref for "state/Dockerfile".
STATE_GIT_REF=$(git rev-list --abbrev-commit --max-count 1 HEAD -- state/Dockerfile)

if [ "x${CACHED_REF}" != "x${STATE_GIT_REF}" ]; then
  run docker build \
    --rm=false \
    --build-arg GIT_REF="${STATE_GIT_REF}" \
    -t jumanjiman/state \
    state/

  run docker tag jumanjiman/state jumanjiman/state:"${STATE_GIT_REF}"
  run touch /dev/shm/publish_state

  if [ -d ~/deps ]; then
    rm -f ~/deps/state.tar || :
    run docker save -o ~/deps/state.tar jumanjiman/state jumanjiman/state:"${STATE_GIT_REF}"
  fi
fi

run docker images | grep -e REPOSITORY -e devenv -e state
