#!/bin/bash
set -eEu
set -o pipefail

################################################################################
# Clean up previous test runs. Invoke as "ci/clean".
################################################################################

. ci/functions.sh

run docker rm -fv test-state test-app || :
