#!/bin/bash
set -eEu
set -o pipefail

################################################################################
# Show helpful information. Invoke as "ci/info".
################################################################################

. ci/functions.sh

run docker version
run docker info
