#!/bin/bash
set -eEu
set -o pipefail

################################################################################
# Publish images to docker hub. Invoke as "ci/publish".
################################################################################

. ci/functions.sh

# shellcheck disable=SC2154
docker login -u "${user}" -p "${pass}"

if [ -e /dev/shm/publish_state ]; then
  # Latest git ref for "state/Dockerfile".
  STATE_GIT_REF="$(git rev-list --abbrev-commit --max-count 1 HEAD -- state/Dockerfile)"

  run docker push jumanjiman/state:"${STATE_GIT_REF}"
fi

for image in $(docker images | awk '/jumanjiman\/devenv/ {print $1":"$2 }'); do
  run docker push "${image}"
done

docker logout
