#!/bin/bash
set -eEu
set -o pipefail

################################################################################
# Run the test harness. Invoke as "ci/test".
################################################################################

. ci/functions.sh

echo
echo 'Check files for shell style, binaries, and whitespace.'
ci/check-files -d

echo
echo 'Check functionality of the hc command.'
app/usr/bin/hc -b fixtures/hc/ -t build -t runtime -r5 -c20
