#!/bin/bash
set -eEu
set -o pipefail

################################################################################
# Run the test harness. Invoke as "ci/test".
################################################################################

. ci/bootstrap

info 'Clean up from previous runs.'
ci/clean

info 'Check files for shell style, binaries, and whitespace.'
run pre-commit run --all-files --hook-stage manual

info 'Check functionality of the hc command.'
run app/usr/bin/hc -b fixtures/hc/ -t build -t runtime -r5 -c20 -f documentation

info 'Run static build tests.'
run docker run --rm -it --entrypoint=hc jumanjiman/devenv -t build -f documentation

info 'Run runtime tests.'
run docker create --name test-state jumanjiman/state true
run docker run -d --volumes-from test-state --name=test-app jumanjiman/devenv
run docker exec -it test-app hc -t runtime -r5 -f silent

info 'Clean up.'
ci/clean
